/**
 * This 3D island model and its geometry were generated by Claude AI.
 * Source: https://claude.ai/share/acf4890f-328e-4f25-bd1e-905e6ee78e57
 */

import { IFloatingIslandProps } from '@/shared/types/types';
import { useFrame } from '@react-three/fiber';
import { FC, useMemo, useRef } from "react";
import * as THREE from 'three';

export const FloatingIsland: FC<IFloatingIslandProps> = ({ animation = true }) => {
    const groupRef = useRef<THREE.Group>(null!);

    useFrame((state) => {
        const t = state.clock.getElapsedTime();
        if (groupRef.current && animation) {
            groupRef.current.rotation.y = t * 0.4;
            groupRef.current.position.y = Math.sin(t * 1.5) * 0.08;
        }
    });

    const islandGeometry = useMemo(() => {
        const segments = 12;
        const heightSegments = 8;
        const geo = new THREE.ConeGeometry(1.6, 2.4, segments, heightSegments, false);
        geo.rotateX(Math.PI);

        const posAttr = geo.attributes.position;
        const vertex = new THREE.Vector3();

        let seed = 42;
        const rand = () => {
            seed = (seed * 16807 + 0) % 2147483647;
            return (seed - 1) / 2147483646;
        };

        for (let i = 0; i < posAttr.count; i++) {
            vertex.fromBufferAttribute(posAttr, i);

            const normalizedY = (vertex.y + 1.2) / 2.4; // 0 = bottom tip, 1 = top
            const distFromAxis = Math.sqrt(vertex.x * vertex.x + vertex.z * vertex.z);

            if (distFromAxis < 0.05) continue;

            const bulgeFactor = Math.sin(normalizedY * Math.PI) * 0.25;
            const angle = Math.atan2(vertex.z, vertex.x);

            const edgeNoise = (rand() - 0.5) * 0.18 * (1 - normalizedY * 0.5);

            const angularVariation = Math.sin(angle * 3 + 1.2) * 0.08 + Math.cos(angle * 5) * 0.05;

            const radialOffset = bulgeFactor + edgeNoise + angularVariation;

            vertex.x += (vertex.x / (distFromAxis + 0.001)) * radialOffset;
            vertex.z += (vertex.z / (distFromAxis + 0.001)) * radialOffset;

            if (normalizedY > 0.1 && normalizedY < 0.95) {
                vertex.y += (rand() - 0.5) * 0.12;
            }

            posAttr.setXYZ(i, vertex.x, vertex.y, vertex.z);
        }

        geo.computeVertexNormals();

        const colors: number[] = [];
        const palette = [
            [0.42, 0.28, 0.18],
            [0.55, 0.38, 0.24],
            [0.62, 0.44, 0.30],
            [0.48, 0.33, 0.20],
            [0.38, 0.25, 0.16],
            [0.70, 0.52, 0.36],
            [0.52, 0.36, 0.22],
            [0.45, 0.30, 0.17],
        ];

        for (let i = 0; i < posAttr.count; i += 3) {
            vertex.fromBufferAttribute(posAttr, i);
            const normalizedY = (vertex.y + 1.2) / 2.4;
            const heightBias = normalizedY < 0.3 ? 0 : Math.floor(normalizedY * 4) % palette.length;
            const c = palette[(heightBias + Math.floor(rand() * 3)) % palette.length];
            for (let j = 0; j < 3; j++) {
                colors.push(c[0], c[1], c[2]);
            }
        }

        geo.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
        return geo;
    }, []);

    const rimGeometry = useMemo(() => {
        const geo = new THREE.CylinderGeometry(1.7, 1.8, 0.16, 32);
        const posAttr = geo.attributes.position;
        let seed = 99;
        const rand = () => {
            seed = (seed * 16807) % 2147483647;
            return (seed - 1) / 2147483646;
        };
        for (let i = 0; i < posAttr.count; i++) {
            const x = posAttr.getX(i);
            const y = posAttr.getY(i);
            const z = posAttr.getZ(i);
            const r = Math.sqrt(x * x + z * z);
            if (r > 0.5) {
                const bump = (rand() - 0.5) * 0;
                posAttr.setXYZ(i, x + (x / r) * bump, y, z + (z / r) * bump);
            }
        }
        geo.computeVertexNormals();
        return geo;
    }, []);

    return (
        <group scale={[0.65, 0.65, 0.65]} ref={groupRef}>

            <mesh position={[0, 0, 0]} geometry={islandGeometry}>
                <meshStandardMaterial
                    vertexColors
                    flatShading
                    roughness={0.92}
                    metalness={0.0}
                />
            </mesh>

            <mesh position={[0, 1.15, 0]} geometry={rimGeometry}>
                <meshStandardMaterial
                    color="#6b4423"
                    roughness={0.88}
                    flatShading
                />
            </mesh>

            <group position={[0, -1.4, 0]} scale={[1, 1, 0.6]}>
                <mesh rotation={[-Math.PI / 2, 0, 0]}>
                    <circleGeometry args={[0.55, 32]} />
                    <meshBasicMaterial color="#c4a49a" transparent opacity={0.3} />
                </mesh>
            </group>
        </group>
    );
};