/**
 * This 3D island model and its geometry were generated by Claude AI.
 * Source: https://claude.ai/share/acf4890f-328e-4f25-bd1e-905e6ee78e57
 */

import { ISLAND_HEIGHT } from '@/shared/const/chapter.const';
import { EIslandModels } from '@/shared/types/enums';
import { IFloatingIslandProps } from '@/shared/types/types';
import { useFrame } from '@react-three/fiber/native';
import { FC, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { Model } from './Model.component';

export const modelAssets = {
    coffee_bag: require('../../../assets/models/coffee_bag.glb'),
    coffee_tamper: require('../../../assets/models/coffee_tamper.glb'),
    coffee_fruit: require('../../../assets/models/coffee_fruit.glb'),
    turkish_coffee_pot: require('../../../assets/models/turkish_coffee_pot.glb'),
    espresso: require('../../../assets/models/espresso.glb'),
    french_press: require('../../../assets/models/french_press.glb'),
    grind_size: require('../../../assets/models/grind_size.glb'),
    milk_pitcher: require('../../../assets/models/milk_pitcher.glb'),
    moka_pot: require('../../../assets/models/moka_pot.glb'),
    portafilter: require('../../../assets/models/portafilter.glb'),
    aeropress: require('../../../assets/models/aeropress.glb'),
    pour_over: require('../../../assets/models/pour_over.glb'),
    gooseneck_kettle: require('../../../assets/models/gooseneck_kettle.glb'),
    puck_prep: require('../../../assets/models/puck_prep.glb'),
    coffee_cup: require('../../../assets/models/coffee_cup.glb'),
};

export const FloatingIsland: FC<IFloatingIslandProps & { modelUrl?: EIslandModels | null }> = ({
    scale,
    position,
    animation = true,
    modelUrl,
}) => {
    const groupRef = useRef<THREE.Group>(null!);

    const modelSrc =
        (modelUrl && modelAssets[modelUrl as keyof typeof modelAssets]) || modelAssets.coffee_cup;

    const baseRotationY = 0;

    useFrame((state) => {
        if (!animation) return;
        const t = state.clock.getElapsedTime();
        if (groupRef.current && animation) {
            groupRef.current.rotation.y = baseRotationY + t * 0.4;
            groupRef.current.position.y = Math.sin(t * 1.5) * 0.08;
        }
    });

    const islandGeometry = useMemo(() => {
        const segments = 10;
        const heightSegments = 6;
        let geo: THREE.BufferGeometry = new THREE.ConeGeometry(
            1.6,
            2.4,
            segments,
            heightSegments,
            false,
        );
        geo.rotateX(Math.PI);

        geo = geo.toNonIndexed();

        const posAttr = geo.attributes.position;
        const vertex = new THREE.Vector3();

        for (let i = 0; i < posAttr.count; i++) {
            vertex.fromBufferAttribute(posAttr, i);

            const normalizedY = (vertex.y + 1.2) / 2.4; // 0 = bottom tip, 1 = top
            const distFromAxis = Math.sqrt(vertex.x * vertex.x + vertex.z * vertex.z);

            if (distFromAxis < 0.05) continue;

            const bulgeFactor = Math.sin(normalizedY * Math.PI) * 0.25;
            const angle = Math.atan2(vertex.z, vertex.x);

            const pseudoRand = Math.sin(angle * 10 + normalizedY * 20);
            const edgeNoise = pseudoRand * 0.09 * (1 - normalizedY * 0.5);

            const angularVariation = Math.sin(angle * 3 + 1.2) * 0.08 + Math.cos(angle * 5) * 0.05;

            const radialOffset = bulgeFactor + edgeNoise + angularVariation;

            vertex.x += (vertex.x / (distFromAxis + 0.001)) * radialOffset;
            vertex.z += (vertex.z / (distFromAxis + 0.001)) * radialOffset;

            if (normalizedY > 0.1 && normalizedY < 0.95) {
                const yNoise = Math.cos(angle * 8 - normalizedY * 15);
                vertex.y += yNoise * 0.06;
            }

            posAttr.setXYZ(i, vertex.x, vertex.y, vertex.z);
        }

        geo.computeVertexNormals();

        const colors: number[] = [];
        const palette = [
            [0.42, 0.28, 0.18],
            [0.55, 0.38, 0.24],
            [0.62, 0.44, 0.3],
            [0.48, 0.33, 0.2],
            [0.38, 0.25, 0.16],
            [0.7, 0.52, 0.36],
            [0.52, 0.36, 0.22],
            [0.45, 0.3, 0.17],
        ];

        for (let i = 0; i < posAttr.count; i += 3) {
            vertex.fromBufferAttribute(posAttr, i);
            const normalizedY = (vertex.y + 1.2) / 2.4;
            const heightBias = normalizedY < 0.3 ? 0 : Math.floor(normalizedY * 4) % palette.length;

            const angle = Math.atan2(vertex.z, vertex.x);
            const faceRandom = Math.abs(Math.sin(angle * 12 + normalizedY * 34));

            const c = palette[(heightBias + Math.floor(faceRandom * 3)) % palette.length];

            for (let j = 0; j < 3; j++) {
                colors.push(c[0], c[1], c[2]);
            }
        }

        geo.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
        return geo;
    }, []);

    const rimGeometry = useMemo(() => {
        const geo = new THREE.CylinderGeometry(1.75, 1.85, 0.16, 16);
        geo.computeVertexNormals();
        return geo;
    }, []);

    return (
        <group
            scale={scale || [0.5, 0.5, 0.5]}
            position={position || [0, ISLAND_HEIGHT, 0]}
            rotation={[0, baseRotationY, 0]}
            ref={groupRef}
        >
            <mesh position={[0, 0, 0]} geometry={islandGeometry}>
                <meshStandardMaterial vertexColors flatShading roughness={0.92} metalness={0.0} />
            </mesh>

            <mesh position={[0, 1.15, 0]} geometry={rimGeometry}>
                <meshStandardMaterial color="#6b4423" roughness={0.88} flatShading />
            </mesh>

            <Model src={modelSrc} position={[0, 1.2, 0]} size={1} rotation={[0, Math.PI, 0]} />

            <group position={[0, -1.4, 0]} scale={[1, 1, 0.6]}>
                <mesh rotation={[-Math.PI / 2, 0, 0]}>
                    <circleGeometry args={[0.55, 32]} />
                    <meshBasicMaterial color="#c4a49a" transparent opacity={0.3} />
                </mesh>
            </group>
        </group>
    );
};
